---
title: "pca_medium"
author: "JL"
date: "`r Sys.Date()`"
output: html_document
---

```{r}
library(here)
library(tidyverse)
library(patchwork)
library(ggrepel)
```

```{r medium TERM}
traits <- read.csv(here("Data", "cleaned", "BC_bird_traits.csv"))
traits$habitat_density[traits$habitat_density == "dense"] <- 1
traits$habitat_density[traits$habitat_density == "semiopen"] <- 2
traits$habitat_density[traits$habitat_density == "open"] <- 3
traits <- traits %>% 
      select(-any_tree_nest, -live_tree_nest) %>% 
  mutate(cavity_nester = ifelse(nest_category == "cavity", 1, 0), habitat_density = as.numeric(habitat_density))
bc <- traits

positive_medium <- c("Alder Flycatcher", "American Kestrel", "American Robin", "American Three-toed Woodpecker", 
"Black-capped Chickadee", "Black-throated Gray Warbler", "Brewer's Blackbird", "Brewer's Sparrow", 
"Brown Creeper", "Canada Jay", "Canada Goose", "Cassin's Finch", "Cedar Waxwing", "Chipping Sparrow", 
"Clark's Nutcracker", "Connecticut Warbler", "Common Yellowthroat", "Dark-eyed Junco", 
"Downy Woodpecker", "Dusky Flycatcher", "Fox Sparrow", "Hairy Woodpecker", 
"Hermit Thrush", "Northern House Wren", "Lazuli Bunting", "Least Flycatcher", "Lewis's Woodpecker", 
"Lincoln's Sparrow", "MacGillivray's Warbler", "Northern Flicker", "Northern Pygmy-Owl", 
"Pine Siskin", "Red-breasted Nuthatch", "Red-winged Blackbird", "Rock Wren", "Rufous Hummingbird", 
"Savannah Sparrow", "Say's Phoebe", "Song Sparrow", "Spotted Towhee", "Steller's Jay", 
"Swamp Sparrow", "Tennessee Warbler", "Townsend's Solitaire", "Tree Swallow", "Turkey Vulture", 
"Veery", "Warbling Vireo", "Western Screech-Owl", "Western Tanager", "Western Wood-Pewee", 
"White-breasted Nuthatch", "White-crowned Sparrow", 
"White-throated Sparrow", "Winter Wren", "Yellow-bellied Sapsucker", "Yellow-rumped Warbler") 
missing_names <- positive_medium[!(positive_medium %in% traits$common_name)] #do all these names appear in the BC list?

negative_medium <- c("Alder Flycatcher", "Barred Owl", "Black-headed Grosbeak", "Black-throated Gray Warbler", 
"Boreal Chickadee", "Brown Creeper", "Cassin's Vireo", "Chestnut-backed Chickadee", 
"Common Yellowthroat", "Dusky Flycatcher", "Golden-crowned Kinglet", "Great Horned Owl", 
"Hermit Thrush", "MacGillivray's Warbler", "Mountain Chickadee", "Nashville Warbler", 
"Northern Saw-whet Owl", "Northern Waterthrush", "Orange-crowned Warbler", "Ovenbird", 
"Pygmy Nuthatch", "Red-breasted Nuthatch", "Red-eyed Vireo", "Red-naped Sapsucker", 
"Ruby-crowned Kinglet", "Ruffed Grouse", "Swainson's Thrush", "Swamp Sparrow", 
"Townsend's Warbler", "Warbling Vireo", "Western Wood-Pewee", "Yellow-rumped Warbler")
missing_names <- negative_medium[!(negative_medium %in% traits$common_name)] #do all these names appear in the BC list?

null_medium <- c("American Goldfinch", "American Robin", "American Wigeon", "Black-capped Chickadee", 
"Black-headed Grosbeak", "Bufflehead", "Brown Creeper", "Brown-headed Cowbird", 
"Calliope Hummingbird", "Canvasback", "Cassin's Finch", "Cedar Waxwing", "Chipping Sparrow", 
"Clark's Nutcracker", "Common Merganser", "Common Goldeneye", "Common Loon", "Common Raven", 
"Common Yellowthroat", "Dark-eyed Junco", "Downy Woodpecker", "Dusky Flycatcher", 
"Eastern Phoebe", "Evening Grosbeak", "Fox Sparrow", "Green-winged Teal", 
"Hammond's Flycatcher", "Hermit Thrush", "House Finch", "Lesser Scaup", "Lincoln's Sparrow", 
"MacGillivray's Warbler", "Mallard", "Marsh Wren", "Mountain Chickadee", "Mourning Dove", 
"Nashville Warbler", "Northern Pintail", "Northern Shoveler", "Northern Waterthrush", 
"Olive-sided Flycatcher", "Orange-crowned Warbler", "Pacific Wren", "Pine Grosbeak", 
"Pine Siskin", "Pileated Woodpecker", "Red Crossbill", "Red-breasted Merganser", 
"Red-breasted Nuthatch", "Red-naped Sapsucker", "Red-tailed Hawk", "Ring-necked Duck", 
"Rock Wren", "Ruby-crowned Kinglet", "Ruffed Grouse", "Rufous Hummingbird", "Song Sparrow", 
 "Steller's Jay", "Surf Scoter", "Swainson's Thrush", "Townsend's Warbler", 
"Varied Thrush", "Violet-green Swallow", "Warbling Vireo", "Western Tanager", 
"White-breasted Nuthatch", "White-crowned Sparrow", "White-winged Scoter", "Willow Flycatcher", 
"Wilson's Warbler", "Williamson's Sapsucker", "Winter Wren", "Yellow Warbler", 
"Yellow-bellied Flycatcher", "Yellow-rumped Warbler")
missing_names <- null_medium[!(null_medium %in% traits$common_name)] #do all these names appear in the BC list?

traits$positive_medium <- ifelse(traits$common_name %in% positive_medium, 1, NA)
traits$negative_medium <- ifelse(traits$common_name %in% negative_medium, 1, NA)
traits$null_medium <- ifelse(traits$common_name %in% null_medium, 1, NA)

traits <- traits %>%
    filter(!if_all(c(positive_medium, negative_medium, null_medium), is.na)) %>% 
    mutate(across(c(positive_medium, negative_medium, null_medium), ~replace_na(.x, 0)))
```

```{r}
trait.pca <- traits %>% 
  select(common_name, where(is.numeric), -elevational_range,-positive_medium, -negative_medium, -null_medium,  -kipps_distance, -repro_age, -clutches_per_year, -lifespan, -eco_spec_index, -ends_with("_id"), -fstimb)

pca_result <- prcomp(trait.pca[,-1], scale = T)
##
pca_result$rotation
pca_result$x
biplot(pca_result)
pca_loadings <- as.data.frame(pca_result$rotation) %>% select(1:10)

summary(pca_result)
VE <- pca_result$sdev^2
PVE <- VE / sum(VE)
PVE <- round(PVE, 2)

pve_df <- data.frame(
  PC = 1:length(PVE),
  PVE = PVE)

(scree <- ggplot(pve_df, aes(x = PC, y = PVE)) +
  geom_col() +
  xlab("Principal Component") +
  ylab("Proportion of Variance Explained") +
  ggtitle("Scree Plot") +
  ylim(0, 1) +
    theme_bw()+
  scale_x_continuous(breaks = 1:length(PVE)))
ggsave(here("Figures", "PCA", "scree plot.medium.png"), plot = scree, width = 8, height =8)

##
pca_df <- as.data.frame(pca_result$x) %>%
  bind_cols(traits %>% select(common_name, positive_medium, negative_medium, null_medium))
pca_df <- pca_df %>%
  mutate(fire_response = case_when(
    positive_medium == 1 & negative_medium == 0 & null_medium == 0 ~ "Positive",
    positive_medium == 0 & negative_medium == 1 & null_medium == 0 ~ "Negative",
    positive_medium == 0 & negative_medium == 0 & null_medium == 1 ~ "Neutral",
    positive_medium == 1 & negative_medium == 1 & null_medium == 0 ~ "Positive & Negative",
    positive_medium == 1 & null_medium == 1 & negative_medium == 0 ~ "Positive & Neutral",
    negative_medium == 1 & null_medium == 1 & positive_medium == 0 ~ "Negative & Neutral",
    TRUE ~ "None"
  ))

loadings <- as.data.frame(pca_result$rotation)  # columns = PCs, rows = traits
loadings$trait <- rownames(loadings)

# Optional: scale arrows for visualization
arrow_multiplier <- 5  # adjust to make arrows visible
loadings <- loadings %>%
  mutate(PC1_arrow = PC1 * arrow_multiplier,
         PC2_arrow = PC2 * arrow_multiplier)
```
# 
```{r}
pca_scores <- as.data.frame(pca_result$x)
pca_scores$common_name <- traits$common_name
pca_scores$positive <- traits$positive
pca_scores$negative <- traits$negative
pca_scores$null <- traits$null
```

```{r}
# Extract loadings
loadings <- as.data.frame(pca_result$rotation)

#Add trait names as a column
loadings$trait <- rownames(loadings)

loadings_long <- loadings %>%
  pivot_longer(cols = starts_with("PC"),
               names_to = "PC",
               values_to = "loading") %>%
  filter(PC %in% paste0("PC", 1:2))   # keep only PCs 1-5

(loadings.bar <- ggplot(loadings_long, aes(x = trait, y = loading, fill = PC)) +
  geom_col(position = "dodge") + 
  coord_flip() + 
  labs(x = "Trait", y = "Loading") +
  theme_bw(base_size = 14) +
  scale_y_continuous(limits = c(-0.5, 0.5), breaks = seq(-0.5, 0.5, 0.25)) +  # set range and breaks
  scale_fill_manual(values = c("#a1d99b", "#688c64")) +
  facet_wrap(~PC)+
    theme(legend.position = "none"))

ggsave(here("Figures", "PCA", "loadings bar plot.medium.png"), plot = loadings.bar, width = 6, height =5, dpi = 300)

loadings %>%  arrange(desc(abs(PC1)))
```

```{r}
bc <- bc %>%  
  select(common_name, where(is.numeric), -elevational_range,  -kipps_distance, -repro_age, -clutches_per_year, -lifespan, -eco_spec_index, -ends_with("_id"), -fstimb) %>% 
  drop_na()  

#plotting all bc spp on this pca:
bc_scaled <- scale(bc[,-1], center = (pca_result$center), scale = (pca_result$scale))

bc_scores <- as.data.frame(as.matrix(bc_scaled) %*% pca_result$rotation)
```

```{r}
bc_scores$common_name <- bc$common_name
centers <- data.frame(
  group = c("positive", "mixed", "negative", "neutral"),
  PC1 = c(
    mean(pca_scores$PC1[pca_scores$positive == 1 & pca_scores$negative != 1], na.rm = TRUE),
    mean(pca_scores$PC1[pca_scores$positive == 1 & pca_scores$negative == 1], na.rm = TRUE),
    mean(pca_scores$PC1[pca_scores$negative == 1 & pca_scores$positive != 1], na.rm = TRUE),
    mean(pca_scores$PC1[pca_scores$null == 1 & pca_scores$positive == 0 & pca_scores$negative == 0], na.rm = TRUE)),
  PC2 = c(
    mean(pca_scores$PC2[pca_scores$positive == 1 & pca_scores$negative != 1], na.rm = TRUE),
    mean(pca_scores$PC2[pca_scores$positive == 1 & pca_scores$negative == 1], na.rm = TRUE),
    mean(pca_scores$PC2[pca_scores$negative == 1 & pca_scores$positive != 1], na.rm = TRUE),
    mean(pca_scores$PC2[pca_scores$null == 1 & pca_scores$positive == 0 & pca_scores$negative == 0], na.rm = TRUE)
  )
)
pca_scores <- pca_scores %>%
  mutate(fire_response = case_when(
    positive == 1 & negative == 1 ~ "mixed",
    positive == 1 & negative == 0 ~ "positive",
    negative == 1 & positive == 0 ~ "negative",
    TRUE ~ "neutral"
  ))
anova_pc1 <- aov(PC1 ~ fire_response, data = pca_scores)
summary(anova_pc1)

# Post-hoc (Tukey) test for pairwise comparisons
TukeyHSD(anova_pc1)

anova_pc2 <- aov(PC2~ fire_response, data = pca_scores)
summary(anova_pc2)

# Post-hoc (Tukey) test for pairwise comparisons
TukeyHSD(anova_pc2)

# Original PCA points
orig_df <- pca_scores
orig_df$type <- "PCA"
# New projected points
new_df <- bc_scores
new_df$common_name <- bc$common_name[complete.cases(bc)]

# Combine
plot_df <- left_join(new_df,orig_df)
(with.mix <- ggplot(pca_scores) +
  geom_point(data = new_df, aes( x = PC1, y = PC2), shape = 1, color = "grey", alpha = 0.85, size = 3)+
  geom_point(aes(PC1, PC2), color = "grey50", size =3) +
  geom_point(data = subset(pca_scores, positive == 1),
             aes(PC1, PC2), color = "#0072B2", size = 4, alpha = 0.8) +
  geom_point(data = subset(pca_scores, negative == 1),
             aes(PC1, PC2), color = "#D55E00", size = 4, alpha = 0.8) +
  geom_point(data = subset(pca_scores, negative == 1& positive == 1),
             aes(PC1, PC2), color = "darkmagenta", size = 4, alpha = 0.8)+
  geom_point(data = centers, aes(PC1, PC2, color = group), size = 13, shape = 8) +
  scale_color_manual(values = c("darkmagenta", "#D55E00","grey50","#0072B2")) +
  theme_bw() +
  theme(legend.position="bottom")+
   labs(color = "Short Fire Response",
       title = "",x = paste0("PC1 (", round(summary(pca_result)$importance[2,1]*100, 1), "%)"),
    y = paste0("PC2 (", round(summary(pca_result)$importance[2,2]*100, 1), "%)")))
#ggsave(here("Figures", "PCA", "PCA_centers.medium.png"), plot = with.mix, width = 8, height =8, dpi = 300)

arrow_multiplier <- 5  # adjust to make arrows visible
loadings <- loadings %>%
  mutate(PC1_arrow = PC1 * arrow_multiplier,
         PC2_arrow = PC2 * arrow_multiplier)
(f2 <- ggplot() +
  geom_segment(data = loadings,
               aes(x = 0, y = 0, xend = PC1_arrow, yend = PC2_arrow),
               arrow = arrow(length = unit(0.3, "cm")),
               color = "black") +
  geom_text_repel(data = loadings,
                  aes(x = PC1_arrow, y = PC2_arrow, label = trait),
                  color = "black",
                  size = 4.5,
                  segment.color = "grey50",    # line from label to point
                  segment.size = 0.5,
                  segment.alpha = 0.8,
                  nudge_x = 0,                 # optional small nudge
                  nudge_y = 0,
                  box.padding = 0.5,
                  point.padding = 0.5,
                  max.overlaps = 20) +
  geom_point(data = centers, aes(PC1, PC2, color = group), size = 10, shape = 8) +
  theme_bw() +
  theme(legend.position = "none")+
  scale_color_manual(values = c("darkmagenta", "#D55E00","grey50","#0072B2")) +
  labs(x = paste0("PC1 (", round(summary(pca_result)$importance[2,1]*100, 1), "%)"),
    y = paste0("PC2 (", round(summary(pca_result)$importance[2,2]*100, 1), "%)")))

(medium <- with.mix/f2+  
  plot_layout(guides = "collect") +
  plot_annotation(theme = theme(legend.position = "bottom"), tag_levels = "A")&
  theme(
    text        = element_text(size = 20),
    axis.text   = element_text(size = 18),
    axis.title  = element_text(size = 20),
    strip.text  = element_text(size = 20),
    legend.text = element_text(size = 16),
    legend.title= element_text(size = 18)))
ggsave(here("Figures", "PCA", "PCA_end fig medium.png"), plot = medium,width = 10, height =13, dpi = 1000)
```